# Generated by Django 6.0.5 on 2026-05-20 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('hospital_name', models.CharField(max_length=256)),
                ('specialization', models.CharField(max_length=128)),
                ('medical_license_number', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid license number.', regex='^[A-Z0-9\\-]{6,24}$')])),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('hospital_email_domain', models.CharField(blank=True, max_length=128)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_doctor_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
